### ISSUE TITLE
Make `/api_v1` redirect to `api_v1/ui`

### ISSUE THREAD

**Issue by SimonGoring** [EarthLifeConsortium/elc_api#1]
So that users will see help and overview right away instead of getting the current 404.

**Comment by SimonGoring** [comment]
I tried to work on this over the weekend and really have no idea how to do it.

**Comment by jpjenk** [comment]
The default routing probably works this way intentionally because everything (including the UI) should be associated with a particular API version. However, according to:

https://connexion.readthedocs.io/en/latest/routing.html#endpoint-routing-to-your-python-views

the automatic routing can be over ridden using the RestyResolver function which is included with the Connexion framework. This deviates from the standard OpenAPI spec though, that's why you can't specify this behavior in the swagger definition file (ie. its not a Python/Flask issue).

The best (and certainly simplest) way to handle this routing issue, in my opinion, is on the frontend server when the API is deployed.

**Comment by jpjenk** [comment]
The user interface (aka the Sandbox) is handled as a route within the API itself and shouldn't be the base path itself. This is probably appropriate.
